"use client";

import { useState } from "react";

type Props = {
	projectId: string;
	conceptId: string;
	model: string;
	imageUrl: string;
	thumbnailUrl?: string;
};

export function RenderCard({ projectId, conceptId, model, imageUrl, thumbnailUrl }: Props) {
	const [saving, setSaving] = useState(false);
	const [savedId, setSavedId] = useState<string | null>(null);

	async function onSave() {
		if (saving || savedId) return;
		setSaving(true);
		try {
			const res = await fetch("/api/save", {
				method: "POST",
				headers: { "content-type": "application/json" },
				body: JSON.stringify({ projectId, conceptId, model, imageUrl, thumbnailUrl }),
			});
			const data = await res.json();
			if (data.renderId) setSavedId(data.renderId);
		} catch (err) {
			console.error("Save failed:", err);
		} finally {
			setSaving(false);
		}
	}

	function getModelLabel(model: string): string {
		switch (model) {
			case "v2-stable-diffusion-xl":
				return "SDXL Inpainting";
			case "v2-dalle-2":
				return "DALL-E 2";
			case "v1-seedream":
				return "v1 Seedream";
			case "v1_5-openai":
				return "v1.5 OpenAI";
			default:
				return model;
		}
	}

	return (
		<div className="rounded-lg border border-gray-200 p-3 flex flex-col gap-3 bg-white shadow-sm">
			<div className="text-xs text-gray-600 font-medium">{getModelLabel(model)}</div>
			<a href={imageUrl} target="_blank" rel="noreferrer" className="block">
				<img src={thumbnailUrl ?? imageUrl} alt={`Generated by ${getModelLabel(model)}`} className="w-full h-auto rounded-md bg-gray-50" />
			</a>
			<div className="flex items-center gap-2">
				<a
					href={imageUrl}
					download
					className="button-primary flex-1 justify-center text-center"
				>
					Download
				</a>
				<button
					onClick={onSave}
					disabled={saving || !!savedId}
					className="button-secondary flex-1 justify-center"
				>
					{savedId ? "Saved" : saving ? "Saving..." : "Save"}
				</button>
			</div>
		</div>
	);
} 